num = int(input("Enter a number: "))

print("+----------------------+")
print(f"| {'MULTIPLICATION: ' + str(num):^20} |")
print("+-----------+----------+")
print(f"| {f'{num} x {1}':^9} | {num*1:^8} |")
print("+-----------+----------+")
print(f"| {f'{num} x {2}':^9} | {num*2:^8} |")
print("+-----------+----------+")
print(f"| {f'{num} x {3}':^9} | {num*3:^8} |")
print("+-----------+----------+")
print(f"| {f'{num} x {4}':^9} | {num*4:^8} |")
print("+-----------+----------+")
print(f"| {f'{num} x {5}':^9} | {num*5:^8} |")
print("+-----------+----------+")